namespace Knife.Enums {
    enum ButtonCode {
        Invalid = -1,
        None = 0,

        KeyFirst = 0,

        KeyNone = KeyFirst,
        Key0,
        Key1,
        Key2,
        Key3,
        Key4,
        Key5,
        Key6,
        Key7,
        Key8,
        Key9,
        KeyA,
        KeyB,
        KeyC,
        KeyD,
        KeyE,
        KeyF,
        KeyG,
        KeyH,
        KeyI,
        KeyJ,
        KeyK,
        KeyL,
        KeyM,
        KeyN,
        KeyO,
        KeyP,
        KeyQ,
        KeyR,
        KeyS,
        KeyT,
        KeyU,
        KeyV,
        KeyW,
        KeyX,
        KeyY,
        KeyZ,
        KeyPad0,
        KeyPad1,
        KeyPad2,
        KeyPad3,
        KeyPad4,
        KeyPad5,
        KeyPad6,
        KeyPad7,
        KeyPad8,
        KeyPad9,
        KeyPadDivide,
        KeyPadMultiply,
        KeyPadMinus,
        KeyPadPlus,
        KeyPadEnter,
        KeyPadDecimal,
        KeyLbracket,
        KeyRbracket,
        KeySemicolon,
        KeyApostrophe,
        KeyBackquote,
        KeyComma,
        KeyPeriod,
        KeySlash,
        KeyBackslash,
        KeyMinus,
        KeyEqual,
        KeyEnter,
        KeySpace,
        KeyBackspace,
        KeyTab,
        KeyCapslock,
        KeyNumlock,
        KeyEscape,
        KeyScrolllock,
        KeyInsert,
        KeyDelete,
        KeyHome,
        KeyEnd,
        KeyPageup,
        KeyPagedown,
        KeyBreak,
        KeyLshift,
        KeyRshift,
        KeyLalt,
        KeyRalt,
        KeyLcontrol,
        KeyRcontrol,
        KeyLwin,
        KeyRwin,
        KeyApp,
        KeyUp,
        KeyLeft,
        KeyDown,
        KeyRight,
        KeyF1,
        KeyF2,
        KeyF3,
        KeyF4,
        KeyF5,
        KeyF6,
        KeyF7,
        KeyF8,
        KeyF9,
        KeyF10,
        KeyF11,
        KeyF12,
        KeyCapslocktoggle,
        KeyNumlocktoggle,
        KeyScrolllocktoggle,

        KeyLast = KeyScrolllocktoggle,
        KeyCount = KeyLast - KeyFirst + 1,

        // Mouse
        MouseFirst = KeyLast + 1,

        MouseLeft = MouseFirst,
        MouseRight,
        MouseMiddle,
        Mouse4,
        Mouse5,
        MouseWheelUp,     // A fake button which is 'pressed' and 'released' when the wheel is moved up 
        MouseWheelDown,   // A fake button which is 'pressed' and 'released' when the wheel is moved down

        MouseLast = MouseWheelDown,
        MouseCount = MouseLast - MouseFirst + 1,
    };

}
